In \[1\]:

    import pandas as pd
    import numpy as np
    from sklearn.model_selection import train_test_split
    from sklearn.preprocessing import LabelEncoder
    from sklearn import tree

In \[2\]:

    df=pd.read_csv("D:/ML/DATASETS/beginers data set/beginner_datasets/bank.csv")
    df.head()

Out\[2\]:

|     | age | job          | marital | education | default | balance | housing | loan | contact | day | month | duration | campaign | pdays | previous | poutcome | deposit |
|-----|-----|--------------|---------|-----------|---------|---------|---------|------|---------|-----|-------|----------|----------|-------|----------|----------|---------|
| 0   | 58  | management   | married | tertiary  | no      | 2143    | yes     | no   | unknown | 5   | may   | 261      | 1        | -1    | 0        | unknown  | no      |
| 1   | 44  | technician   | single  | secondary | no      | 29      | yes     | no   | unknown | 5   | may   | 151      | 1        | -1    | 0        | unknown  | no      |
| 2   | 33  | entrepreneur | married | secondary | no      | 2       | yes     | yes  | unknown | 5   | may   | 76       | 1        | -1    | 0        | unknown  | no      |
| 3   | 47  | blue-collar  | married | unknown   | no      | 1506    | yes     | no   | unknown | 5   | may   | 92       | 1        | -1    | 0        | unknown  | no      |
| 4   | 33  | unknown      | single  | unknown   | no      | 1       | no      | no   | unknown | 5   | may   | 198      | 1        | -1    | 0        | unknown  | no      |

In \[3\]:

    df.isnull().sum()

Out\[3\]:

    age          0
    job          0
    marital      0
    education    0
    default      0
    balance      0
    housing      0
    loan         0
    contact      0
    day          0
    month        0
    duration     0
    campaign     0
    pdays        0
    previous     0
    poutcome     0
    deposit      0
    dtype: int64

In \[11\]:

    col=df.columns

In \[12\]:

    col

Out\[12\]:

    Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
           'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
           'previous', 'poutcome', 'deposit'],
          dtype='object')

In \[17\]:

    df["job"]=LabelEncoder().fit_transform(df["job"])
    df["marital"]=LabelEncoder().fit_transform(df["marital"])
    df["education"]=LabelEncoder().fit_transform(df["education"])
    df["default"]=LabelEncoder().fit_transform(df["default"])
    df["housing"]=LabelEncoder().fit_transform(df["housing"])
    df["loan"]=LabelEncoder().fit_transform(df["loan"])
    df["contact"]=LabelEncoder().fit_transform(df["contact"])
    df["month"]=LabelEncoder().fit_transform(df["month"])
    df["poutcome"]=LabelEncoder().fit_transform(df["poutcome"])
    df["deposit"]=LabelEncoder().fit_transform(df["deposit"])

In \[18\]:

    df

Out\[18\]:

|       | age | job | marital | education | default | balance | housing | loan | contact | day | month | duration | campaign | pdays | previous | poutcome | deposit |
|-------|-----|-----|---------|-----------|---------|---------|---------|------|---------|-----|-------|----------|----------|-------|----------|----------|---------|
| 0     | 58  | 4   | 1       | 2         | 0       | 2143    | 1       | 0    | 2       | 5   | 8     | 261      | 1        | -1    | 0        | 3        | 0       |
| 1     | 44  | 9   | 2       | 1         | 0       | 29      | 1       | 0    | 2       | 5   | 8     | 151      | 1        | -1    | 0        | 3        | 0       |
| 2     | 33  | 2   | 1       | 1         | 0       | 2       | 1       | 1    | 2       | 5   | 8     | 76       | 1        | -1    | 0        | 3        | 0       |
| 3     | 47  | 1   | 1       | 3         | 0       | 1506    | 1       | 0    | 2       | 5   | 8     | 92       | 1        | -1    | 0        | 3        | 0       |
| 4     | 33  | 11  | 2       | 3         | 0       | 1       | 0       | 0    | 2       | 5   | 8     | 198      | 1        | -1    | 0        | 3        | 0       |
| ...   | ... | ... | ...     | ...       | ...     | ...     | ...     | ...  | ...     | ... | ...   | ...      | ...      | ...   | ...      | ...      | ...     |
| 45206 | 51  | 9   | 1       | 2         | 0       | 825     | 0       | 0    | 0       | 17  | 9     | 977      | 3        | -1    | 0        | 3        | 1       |
| 45207 | 71  | 5   | 0       | 0         | 0       | 1729    | 0       | 0    | 0       | 17  | 9     | 456      | 2        | -1    | 0        | 3        | 1       |
| 45208 | 72  | 5   | 1       | 1         | 0       | 5715    | 0       | 0    | 0       | 17  | 9     | 1127     | 5        | 184   | 3        | 2        | 1       |
| 45209 | 57  | 1   | 1       | 1         | 0       | 668     | 0       | 0    | 1       | 17  | 9     | 508      | 4        | -1    | 0        | 3        | 0       |
| 45210 | 37  | 2   | 1       | 1         | 0       | 2971    | 0       | 0    | 0       | 17  | 9     | 361      | 2        | 188   | 11       | 1        | 0       |

45211 rows × 17 columns

In \[37\]:

    x=df.drop(["deposit"],axis="columns").values
    x 

Out\[37\]:

    array([[ 58,   4,   1, ...,  -1,   0,   3],
           [ 44,   9,   2, ...,  -1,   0,   3],
           [ 33,   2,   1, ...,  -1,   0,   3],
           ...,
           [ 72,   5,   1, ..., 184,   3,   2],
           [ 57,   1,   1, ...,  -1,   0,   3],
           [ 37,   2,   1, ..., 188,  11,   1]], dtype=int64)

In \[130\]:

    y=df[["deposit"]].values
    y

Out\[130\]:

    array([[0],
           [0],
           [0],
           ...,
           [1],
           [0],
           [0]])

In \[131\]:

    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In \[132\]:

    x_train.shape

Out\[132\]:

    (36168, 16)

In \[133\]:

    x_test.shape

Out\[133\]:

    (9043, 16)

In \[134\]:

    y_train.shape

Out\[134\]:

    (36168, 1)

In \[135\]:

    y_test.shape

Out\[135\]:

    (9043, 1)

In \[136\]:

    model=tree.DecisionTreeClassifier()
    model.fit(x,y)

Out\[136\]:

    DecisionTreeClassifier()

In \[137\]:

    model.score(x,y)

Out\[137\]:

    1.0

In \[138\]:

    model=tree.DecisionTreeClassifier()
    model.fit(x_train,y_train)

Out\[138\]:

    DecisionTreeClassifier()

In \[161\]:

    pre=model.predict(x_test)
    pre=pre.reshape(-1,1)
    pre

Out\[161\]:

    array([[1],
           [0],
           [0],
           ...,
           [0],
           [0],
           [0]])

In \[162\]:

    re=y_test
    re

Out\[162\]:

    array([[0],
           [0],
           [0],
           ...,
           [0],
           [0],
           [0]])

In \[163\]:

    len(pre)

Out\[163\]:

    9043

In \[164\]:

    len(y_test)

Out\[164\]:

    9043

In \[167\]:

    from sklearn.metrics import accuracy_score
    print(accuracy_score(y_test,pre)*100)

    86.79641711821299

In \[169\]:

    from sklearn.metrics import confusion_matrix
    cm=confusion_matrix(y_test,pre)
    cm

Out\[169\]:

    array([[7328,  574],
           [ 620,  521]], dtype=int64)

In \[176\]:

    from sklearn.ensemble import RandomForestClassifier as RF

In \[179\]:

    xx=x
    yy=y

In \[180\]:

    xx

Out\[180\]:

    array([[ 58,   4,   1, ...,  -1,   0,   3],
           [ 44,   9,   2, ...,  -1,   0,   3],
           [ 33,   2,   1, ...,  -1,   0,   3],
           ...,
           [ 72,   5,   1, ..., 184,   3,   2],
           [ 57,   1,   1, ...,  -1,   0,   3],
           [ 37,   2,   1, ..., 188,  11,   1]], dtype=int64)

In \[189\]:

    yy=yy.reshape(-1,1)
    yy

Out\[189\]:

    array([[0],
           [0],
           [0],
           ...,
           [1],
           [0],
           [0]])

In \[190\]:

    x_train,x_test,y_train,y_test=train_test_split(xx,yy,test_size=0.2)

In \[193\]:

    rf_model=RF(n_estimators=500,random_state=1)
    rf_model.fit(x_train,y_train)

    <ipython-input-193-3aae6edcd6a6>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
      rf_model.fit(x_train,y_train)

Out\[193\]:

    RandomForestClassifier(n_estimators=500, random_state=1)

In \[203\]:

    rf_pre=rf_model.predict(x_test)
    rf_pre=rf_pre.reshape(-1,1)
    rf_pre

Out\[203\]:

    array([[0],
           [0],
           [0],
           ...,
           [0],
           [0],
           [0]])

In \[204\]:

    y_test

Out\[204\]:

    array([[0],
           [0],
           [0],
           ...,
           [0],
           [0],
           [0]])

In \[205\]:

    from sklearn.metrics import accuracy_score
    print(accuracy_score(y_test,rf_pre)*100)

    90.39035718235098

In \[206\]:

    from sklearn.metrics import confusion_matrix
    cm=confusion_matrix(y_test,rf_pre)
    cm

Out\[206\]:

    array([[7749,  247],
           [ 622,  425]], dtype=int64)