In \[1\]:

    import pandas as pd
    import numpy as np
    import seaborn as sns
    import matplotlib.pyplot as plt
    from sklearn.model_selection import train_test_split

In \[3\]:

    df=pd.read_csv("/home/divum/ML/DATASETS/heart_failure_clinical_records_dataset.csv")
    df.head()

Out\[3\]:

|     | age  | anaemia | creatinine_phosphokinase | diabetes | ejection_fraction | high_blood_pressure | platelets | serum_creatinine | serum_sodium | sex | smoking | time | DEATH_EVENT |
|-----|------|---------|--------------------------|----------|-------------------|---------------------|-----------|------------------|--------------|-----|---------|------|-------------|
| 0   | 75.0 | 0       | 582                      | 0        | 20                | 1                   | 265000.00 | 1.9              | 130          | 1   | 0       | 4    | 1           |
| 1   | 55.0 | 0       | 7861                     | 0        | 38                | 0                   | 263358.03 | 1.1              | 136          | 1   | 0       | 6    | 1           |
| 2   | 65.0 | 0       | 146                      | 0        | 20                | 0                   | 162000.00 | 1.3              | 129          | 1   | 1       | 7    | 1           |
| 3   | 50.0 | 1       | 111                      | 0        | 20                | 0                   | 210000.00 | 1.9              | 137          | 1   | 0       | 7    | 1           |
| 4   | 65.0 | 1       | 160                      | 1        | 20                | 0                   | 327000.00 | 2.7              | 116          | 0   | 0       | 8    | 1           |

In \[5\]:

    df.columns

Out\[5\]:

    Index(['age', 'anaemia', 'creatinine_phosphokinase', 'diabetes',
           'ejection_fraction', 'high_blood_pressure', 'platelets',
           'serum_creatinine', 'serum_sodium', 'sex', 'smoking', 'time',
           'DEATH_EVENT'],
          dtype='object')

In \[7\]:

    df.shape

Out\[7\]:

    (299, 13)

In \[9\]:

    df.describe()

Out\[9\]:

|       | age        | anaemia    | creatinine_phosphokinase | diabetes   | ejection_fraction | high_blood_pressure | platelets     | serum_creatinine | serum_sodium | sex        | smoking   | time       | DEATH_EVENT |
|-------|------------|------------|--------------------------|------------|-------------------|---------------------|---------------|------------------|--------------|------------|-----------|------------|-------------|
| count | 299.000000 | 299.000000 | 299.000000               | 299.000000 | 299.000000        | 299.000000          | 299.000000    | 299.00000        | 299.000000   | 299.000000 | 299.00000 | 299.000000 | 299.00000   |
| mean  | 60.833893  | 0.431438   | 581.839465               | 0.418060   | 38.083612         | 0.351171            | 263358.029264 | 1.39388          | 136.625418   | 0.648829   | 0.32107   | 130.260870 | 0.32107     |
| std   | 11.894809  | 0.496107   | 970.287881               | 0.494067   | 11.834841         | 0.478136            | 97804.236869  | 1.03451          | 4.412477     | 0.478136   | 0.46767   | 77.614208  | 0.46767     |
| min   | 40.000000  | 0.000000   | 23.000000                | 0.000000   | 14.000000         | 0.000000            | 25100.000000  | 0.50000          | 113.000000   | 0.000000   | 0.00000   | 4.000000   | 0.00000     |
| 25%   | 51.000000  | 0.000000   | 116.500000               | 0.000000   | 30.000000         | 0.000000            | 212500.000000 | 0.90000          | 134.000000   | 0.000000   | 0.00000   | 73.000000  | 0.00000     |
| 50%   | 60.000000  | 0.000000   | 250.000000               | 0.000000   | 38.000000         | 0.000000            | 262000.000000 | 1.10000          | 137.000000   | 1.000000   | 0.00000   | 115.000000 | 0.00000     |
| 75%   | 70.000000  | 1.000000   | 582.000000               | 1.000000   | 45.000000         | 1.000000            | 303500.000000 | 1.40000          | 140.000000   | 1.000000   | 1.00000   | 203.000000 | 1.00000     |
| max   | 95.000000  | 1.000000   | 7861.000000              | 1.000000   | 80.000000         | 1.000000            | 850000.000000 | 9.40000          | 148.000000   | 1.000000   | 1.00000   | 285.000000 | 1.00000     |

In \[10\]:

    df.info()

    <class 'pandas.core.frame.DataFrame'>
    RangeIndex: 299 entries, 0 to 298
    Data columns (total 13 columns):
     #   Column                    Non-Null Count  Dtype  
    ---  ------                    --------------  -----  
     0   age                       299 non-null    float64
     1   anaemia                   299 non-null    int64  
     2   creatinine_phosphokinase  299 non-null    int64  
     3   diabetes                  299 non-null    int64  
     4   ejection_fraction         299 non-null    int64  
     5   high_blood_pressure       299 non-null    int64  
     6   platelets                 299 non-null    float64
     7   serum_creatinine          299 non-null    float64
     8   serum_sodium              299 non-null    int64  
     9   sex                       299 non-null    int64  
     10  smoking                   299 non-null    int64  
     11  time                      299 non-null    int64  
     12  DEATH_EVENT               299 non-null    int64  
    dtypes: float64(3), int64(10)
    memory usage: 30.5 KB

In \[11\]:

    df.isna().sum()

Out\[11\]:

    age                         0
    anaemia                     0
    creatinine_phosphokinase    0
    diabetes                    0
    ejection_fraction           0
    high_blood_pressure         0
    platelets                   0
    serum_creatinine            0
    serum_sodium                0
    sex                         0
    smoking                     0
    time                        0
    DEATH_EVENT                 0
    dtype: int64

In \[12\]:

    df.drop(["time"],axis=1,inplace=True)

In \[14\]:

    df.drop(["sex"],axis=1,inplace=True)

In \[15\]:

    df

Out\[15\]:

|     | age  | anaemia | creatinine_phosphokinase | diabetes | ejection_fraction | high_blood_pressure | platelets | serum_creatinine | serum_sodium | smoking | DEATH_EVENT |
|-----|------|---------|--------------------------|----------|-------------------|---------------------|-----------|------------------|--------------|---------|-------------|
| 0   | 75.0 | 0       | 582                      | 0        | 20                | 1                   | 265000.00 | 1.9              | 130          | 0       | 1           |
| 1   | 55.0 | 0       | 7861                     | 0        | 38                | 0                   | 263358.03 | 1.1              | 136          | 0       | 1           |
| 2   | 65.0 | 0       | 146                      | 0        | 20                | 0                   | 162000.00 | 1.3              | 129          | 1       | 1           |
| 3   | 50.0 | 1       | 111                      | 0        | 20                | 0                   | 210000.00 | 1.9              | 137          | 0       | 1           |
| 4   | 65.0 | 1       | 160                      | 1        | 20                | 0                   | 327000.00 | 2.7              | 116          | 0       | 1           |
| ... | ...  | ...     | ...                      | ...      | ...               | ...                 | ...       | ...              | ...          | ...     | ...         |
| 294 | 62.0 | 0       | 61                       | 1        | 38                | 1                   | 155000.00 | 1.1              | 143          | 1       | 0           |
| 295 | 55.0 | 0       | 1820                     | 0        | 38                | 0                   | 270000.00 | 1.2              | 139          | 0       | 0           |
| 296 | 45.0 | 0       | 2060                     | 1        | 60                | 0                   | 742000.00 | 0.8              | 138          | 0       | 0           |
| 297 | 45.0 | 0       | 2413                     | 0        | 38                | 0                   | 140000.00 | 1.4              | 140          | 1       | 0           |
| 298 | 50.0 | 0       | 196                      | 0        | 45                | 0                   | 395000.00 | 1.6              | 136          | 1       | 0           |

299 rows × 11 columns

In \[16\]:

    def corr(dataset,threshold):
        col_corr=set()
        corr_matrix=dataset.corr()
        for i in range(len(corr_matrix.columns)):
            for j in range(i):
                if abs(corr_matrix.iloc[i,j])>threshold:
                    colname=corr_matrix.columns[i]
                    col_corr.add(colname)
        return col_corr

In \[25\]:

    corr(df,0.7)

Out\[25\]:

    set()

In \[49\]:

    x=df.drop("DEATH_EVENT",axis="columns").values

In \[50\]:

    x

Out\[50\]:

    array([[7.500e+01, 0.000e+00, 5.820e+02, ..., 1.900e+00, 1.300e+02,
            0.000e+00],
           [5.500e+01, 0.000e+00, 7.861e+03, ..., 1.100e+00, 1.360e+02,
            0.000e+00],
           [6.500e+01, 0.000e+00, 1.460e+02, ..., 1.300e+00, 1.290e+02,
            1.000e+00],
           ...,
           [4.500e+01, 0.000e+00, 2.060e+03, ..., 8.000e-01, 1.380e+02,
            0.000e+00],
           [4.500e+01, 0.000e+00, 2.413e+03, ..., 1.400e+00, 1.400e+02,
            1.000e+00],
           [5.000e+01, 0.000e+00, 1.960e+02, ..., 1.600e+00, 1.360e+02,
            1.000e+00]])

In \[47\]:

    y=df["DEATH_EVENT"]

In \[48\]:

    y

Out\[48\]:

    0      1
    1      1
    2      1
    3      1
    4      1
          ..
    294    0
    295    0
    296    0
    297    0
    298    0
    Name: DEATH_EVENT, Length: 299, dtype: int64

In \[82\]:

    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=11)

# MODEL<a href="#MODEL" class="anchor-link">¶</a>

In \[83\]:

    from sklearn.linear_model import LogisticRegression

In \[84\]:

    m_l=LogisticRegression()
    m_l.fit(x_train,y_train)

Out\[84\]:

    LogisticRegression()

**In a Jupyter environment, please rerun this cell to show the HTML
representation or trust the notebook.  
On GitHub, the HTML representation is unable to render, please try
loading this page with nbviewer.org.**

LogisticRegression

    LogisticRegression()

In \[85\]:

    pre=m_l.predict(x_test)
    pre

Out\[85\]:

    array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In \[86\]:

    from sklearn.metrics import accuracy_score,confusion_matrix

In \[87\]:

    cm=confusion_matrix(y_test,pre)

In \[88\]:

    cm

Out\[88\]:

    array([[40,  3],
           [13,  4]])

In \[89\]:

    print(accuracy_score(y_test,pre))

    0.7333333333333333

# Decision Tree<a href="#Decision-Tree" class="anchor-link">¶</a>

In \[90\]:

    from sklearn.tree import DecisionTreeClassifier

In \[91\]:

    m_de=DecisionTreeClassifier()
    m_de.fit(x_train,y_train)

Out\[91\]:

    DecisionTreeClassifier()

**In a Jupyter environment, please rerun this cell to show the HTML
representation or trust the notebook.  
On GitHub, the HTML representation is unable to render, please try
loading this page with nbviewer.org.**

DecisionTreeClassifier

    DecisionTreeClassifier()

In \[92\]:

    pre_de=m_de.predict(x_test)

In \[93\]:

    pre_de

Out\[93\]:

    array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
           0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
           0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0])

In \[94\]:

    cm_de=confusion_matrix(pre_de,y_test)

In \[95\]:

    cm_de

Out\[95\]:

    array([[31, 10],
           [12,  7]])

In \[96\]:

    print(accuracy_score(pre_de,y_test))

    0.6333333333333333

# Random Forest classifier<a href="#Random-Forest-classifier" class="anchor-link">¶</a>

In \[97\]:

    from sklearn.ensemble import RandomForestClassifier

In \[112\]:

    m_rfc=RandomForestClassifier(n_estimators=6)
    m_rfc.fit(x_train,y_train)

Out\[112\]:

    RandomForestClassifier(n_estimators=6)

**In a Jupyter environment, please rerun this cell to show the HTML
representation or trust the notebook.  
On GitHub, the HTML representation is unable to render, please try
loading this page with nbviewer.org.**

RandomForestClassifier

    RandomForestClassifier(n_estimators=6)

In \[113\]:

    p_rfc=m_rfc.predict(x_test)

In \[114\]:

    p_rfc

Out\[114\]:

    array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
           0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In \[115\]:

    cm_rfc=confusion_matrix(p_rfc,y_test)
    cm_rfc

Out\[115\]:

    array([[40, 13],
           [ 3,  4]])

In \[116\]:

    print(accuracy_score(p_rfc,y_test))

    0.7333333333333333

# SVC<a href="#SVC" class="anchor-link">¶</a>

In \[103\]:

    from sklearn import svm

In \[117\]:

    Svc_classifier = svm.SVC(kernel='linear', C=1.0).fit(x_train, y_train)

In \[118\]:

    svc_pre=Svc_classifier.predict(x_test)

In \[119\]:

    print("Linear_kernel",accuracy_score(y_test,svc_pre))

    Linear_kernel 0.7

In \[120\]:

    svc_cm=confusion_matrix(y_test,svc_pre)
    svc_cm

Out\[120\]:

    array([[40,  3],
           [15,  2]])

In \[121\]:

    Svc_classifier_gamma = svm.SVC(kernel='rbf', gamma ="auto",C=1.0).fit(x_train, y_train)

In \[122\]:

    svc_pre_gamma=Svc_classifier_gamma.predict(x_test)

In \[123\]:

    print("rbf kernel",accuracy_score(svc_pre_gamma,y_test))

    rbf kernel 0.7166666666666667

# Result<a href="#Result" class="anchor-link">¶</a>

## RandomForestClassification gives the high accuracy<a href="#RandomForestClassification-gives-the-high-accuracy" class="anchor-link">¶</a>

In \[129\]:

    l=[]
    age=float(input("Enter age : "))
    anaemia=int(input())
    cre=int(input())
    diabetes=(int(input()))
    eject_fract=int(input())
    hbp=int(input())
    plat=float(input())
    serum=float(input())
    serum_sodium=float(input())
    smok=int(input())
    l.append(age)
    l.append(anaemia)
    l.append(cre)
    l.append(diabetes)
    l.append(eject_fract)
    l.append(hbp)
    l.append(plat)
    l.append(serum)
    l.append(serum_sodium)
    l.append(smok)
    l

    Enter age : 45
    0
    2060
    1
    60
    0
    742000
    0.8
    138
    0

Out\[129\]:

    [45.0, 0, 2060, 1, 60, 0, 742000.0, 0.8, 138.0, 0]

In \[130\]:

    l1=[]
    l1.append(l)
    m_rfc.predict(l1)

Out\[130\]:

    array([0])

In \[131\]:

    import pickle

In \[133\]:

    with open('Heart_failure_pickle_model', 'wb') as file:
        pickle.dump(m_rfc,file)

In \[ \]: